transform_quality_to_stars: True
run_oversampling: True
random_state: 27

features:
- fixed acidity
- volatile acidity
- citric acid
- residual sugar
- chlorides
- free sulfur dioxide
- total sulfur dioxide
- density
- pH
- sulphates
- alcohol

target: stars  # stars or quality

samples:
  Schmidt: 5
  Penfolds: 4
  Antinori: 3
  Vega Sicilia: 2
  S-Budget: 1

max_features: 4
max_training_runs: 5
decimals: 1
include_features_in_output: False