transform_quality_to_stars: True
run_oversampling: True
random_state: 27

features:
- fixed acidity
- opacity
- total sulfur dioxide
#- residual sugar
- price
- sediment volume
#- age
- magnesium oxide
#- total potassium
- density
- kcal
- citric acid
- alcohol
- production volume
#- chlorides
#- sulphates
#- volatile acidity
#- residual sugar
#- ph

target: stars  # stars or quality

samples:
  Schmidt: 5
  Penfolds: 4
  Antinori: 3
  Vega Sicilia: 2
  S-Budget: 1

max_features: 3
max_training_runs: 9
decimals: 1
include_features_in_output: False
add_fake_features: True
show_metadata: True