transform_quality_to_stars: True
run_oversampling: True
random_state: 27
target: stars  # stars or quality

samples:
  Schmidt: 5
  Penfolds: 4
  Antinori: 3
  Vega Sicilia: 2
  S-Budget: 1

max_features: 12
decimals: 1
include_features_in_output: False