# For sample extraction
random_state: 27

transform_quality_to_stars: True
target: stars  # stars or quality

samples:
  Schmidt: 5
  Penfolds: 4
  Antinori: 3
  Vega Sicilia: 2
  S-Budget: 1

max_features: 12

include_features_in_output: False